# Generated by Django 5.0.2 on 2024-03-04 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'todo_category',
            },
        ),
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=155)),
                ('task_description', models.TextField(max_length=400)),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], default='P1', max_length=2)),
                ('task_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Open', max_length=15)),
                ('starred', models.BooleanField(default=False)),
                ('task_start_date', models.DateTimeField()),
                ('task_end_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taskcategory', to='todo_app.todocategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'todo task',
                'verbose_name_plural': 'todo tasks',
                'db_table': 'todo_task',
            },
        ),
        migrations.CreateModel(
            name='TodoSubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_name', models.CharField(max_length=155)),
                ('subtask_description', models.TextField(max_length=400)),
                ('subtask_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Open', max_length=15)),
                ('subtask_start_date', models.DateTimeField()),
                ('subtask_end_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='todo_app.todotask')),
            ],
            options={
                'verbose_name': 'todo sub task',
                'verbose_name_plural': 'todo sub tasks',
                'db_table': 'todo_sub_task',
            },
        ),
    ]
