# Generated by Django 5.0.2 on 2024-03-04 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todosubtask',
            name='subtask_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todosubtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todo_app.todotask'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='task_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
